config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'site_surveys/new'

  get 'surveys/new'

  get 'organizations/new'

  root 'static_pages#home'

  get 'help' => 'static_pages#help'

  get 'about' => 'static_pages#about'

  get 'signup' => 'users#new'

  resources :users

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  validates :name, presence: true,
                   length: { maximum: 75 },
                   uniqueness: { case_sensitive: false }

  validates :address1, presence: true,
                       length: { maximum: 125 }

  validates :city, presence: true,
                   length: { maximum: 75 }

  validates :state, presence: true,
                    length: { maximum: 2 }

  validates :zip, presence: true,
                  length: { maximum: 5 }

  validates :phone, presence: true,
                    length: { maximum: 12 }

  validates :url, length: { maximum: 255 },
                  format: { with: /\A#{URI::regexp(['http', 'https'])}\z/ },
                  uniqueness: { case_sensitive: false }
end

app/models/organization_site.rb
class OrganizationSite < ActiveRecord::Base
  belongs_to :organization
end

app/models/site_survey.rb
class SiteSurvey < ActiveRecord::Base
  belongs_to :user
  belongs_to :organzation_site
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }

  validates :first_name, presence: true,
                   length: { maximum: 35 }

  validates :last_name, presence: true,
                       length: { maximum: 35 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, length: { maximum: 255 },
                  format: { with: VALID_EMAIL_REGEX },
                  uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/organization_sites_controller.rb
class OrganizationSitesController < ApplicationController
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  def new
  end
end

app/controllers/site_surveys_controller.rb
class SiteSurveysController < ApplicationController
  def new
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Survey App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email,
                                 :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis
  def full_title(page_title = '')
    base_title = "Survey App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/organization_sites_helper.rb
module OrganizationSitesHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/site_surveys_helper.rb
module SiteSurveysHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.first_name + ' ' + user.last_name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "The Survey App", root_path %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Help",    help_path %></li>
      <li><%= link_to "Login", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Survey App", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container">
      
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>

</body>
</html>

app/views/organizations/new.html.erb
<h1>Organizations#new</h1>
<p>Find me in app/views/organizations/new.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/site_surveys/new.html.erb
<h1>SiteSurveys#new</h1>
<p>Find me in app/views/site_surveys/new.html.erb</p>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>Crucifix small batch cornhole chia, slow-carb 90's ugh DIY flannel PBR put a bird on it. Bushwick distillery hoodie narwhal, jean shorts skateboard stumptown Echo Park Shoreditch street art crucifix lo-fi polaroid. Pork belly pop-up cardigan, cold-pressed Williamsburg gentrify trust fund lo-fi hashtag. Heirloom Tumblr seitan wayfarers leggings, readymade forage hashtag Helvetica PBR mumblecore cold-pressed. Listicle tousled Helvetica, before they sold out Portland blog mlkshk heirloom seitan flannel Odd Future art party. Stumptown roof party kale chips, vegan Brooklyn sartorial letterpress taxidermy chambray polaroid. Seitan semiotics +1 ugh, church-key brunch master cleanse Austin pickled mustache Carles.</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>So you need a little help...?</p>

app/views/static_pages/home.html.erb
<h1>Survey App - Home</h1>
<p>Howdy, welcome to the Survey App.  This will get replaced with something meaningfull real soon...</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control'  %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control'  %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control'  %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.first_name + ' ' + @user.last_name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.first_name %> <%= @user.last_name %>
      </h1>
    </section>
  </aside>
</div>